# Numpy Assignment

### This assignment demonstrates the use of Numpy for numerical computations.

#### The Task include:
- Creating arrays.
- Performing statistical calculations
- Manipulating matrices
- Performing arithmetic operations
- Reshaping arrays

In [1]:
import numpy as np

In [ ]:
# 1. Create a 1D Array from 1 to 20:

arr = np.arange(1, 21)
print("Array:", arr)

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
# A. Statistical Operations:

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))

Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398


In [4]:
# B. Indices of elements greater than 10:

indices = np.where(arr > 10)
print("Indices where elements > 10:", indices)

Indices where elements > 10: (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)


In [5]:
# Create 4x4 array from 1 to 16:

array2d = np.arange(1, 17).reshape(4,4)

print("\n4x4 Array:")
print(array2d)


4x4 Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [6]:
# Transpose:

print("\nTranspose:")
print(array2d.T)


Transpose:
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [7]:
# row-wise sum:

print("\nRow-wise Sum:", np.sum(array2d, axis=1))


Row-wise Sum: [10 26 42 58]


In [10]:
# Column-wise Sum:

print("\nColumn-wise Sum:", np.sum(array2d, axis=0))


Column-wise Sum: [28 32 36 40]


In [13]:
# 3. Random 3x3 arrays

arr1 = np.random.randint(1, 21, (3,3))
arr2 = np.random.randint(1, 21, (3,3))

print("\nArray 1:")
print(arr1)

print("\nArray 2:")
print(arr2)

print("\nAddition:")
print(arr1 + arr2)

print("\nSubtraction:")
print(arr1 - arr2)

print("\nMultiplication:")
print(arr1 * arr2)

print("\nDot Product:")
print(np.dot(arr1, arr2))




Array 1:
[[14 19 20]
 [ 9  1 11]
 [ 3  4 13]]

Array 2:
[[15 10  1]
 [20  5  5]
 [18  7  4]]

Addition:
[[29 29 21]
 [29  6 16]
 [21 11 17]]

Subtraction:
[[ -1   9  19]
 [-11  -4   6]
 [-15  -3   9]]

Multiplication:
[[210 190  20]
 [180   5  55]
 [ 54  28  52]]

Dot Product:
[[950 375 189]
 [353 172  58]
 [359 141  75]]


In [14]:
# Reshape & Slicing

arr3 = np.arange(1,13)

reshaped = arr3.reshape(3,4)

print("\nReshaped Array:")
print(reshaped)

print("\nSliced Array (first two rows and last two columns): ")
print(reshaped[:2, -2:])


Reshaped Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Sliced Array (first two rows and last two columns): 
[[3 4]
 [7 8]]
